# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d913716b4e8355d773f556c03e9203275f29fafb211dae85fe31d2f9e9e421aae1e845501f67c4693884ef8aa515e4186f3637be2be2dde633f34d06595ca91

test:
  secret_key_base: d214db790c7de8f477339feead6f78ffd7115c56467667d2bd5e63ca20ef432e243d83f317ebcca45cf23537bfe2316b773acf08ea612afa68c610be8ca75f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
